platform:
  - x86
  - x64
environment:
  matrix:
  - TARGET: msvc
  - TARGET: gnu
install:
  - ps: |
        if ($env:platform -eq 'x86') {
          $env:arch_expanded = "i686-pc-windows-${env:TARGET}";
          $env:ARCH = "x86";
        } else {
          $env:arch_expanded = "x86_64-pc-windows-${env:TARGET}";
          $env:ARCH = "amd64";
        }
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:arch_expanded}.exe" -FileName "rust-nightly.exe"
  - ps: .\rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - cargo test --verbose --no-default-features
